### ISSUE TITLE
Windows Service does not work

### ISSUE THREAD

**Issue by vishkakkar** [nickfloyd/newrelic-perfmon-plugin#19]
I installed the plugin as per the documentation for windows service but it never starts. I am getting this error. Please help!

Child process [7304 - C:\PerfLogs\newrelic-perfmon-plugin-master\standalone\perfmon_plugin_standalone\perfmon_plugin_standalone\perfmon_plugin_standalone.exe ] terminated with 1

**Comment by sschwartzman** [comment]
We'll be publishing a replacement plugin for this one, please look out for that. I'll post a link to it when it gets published.

Thanks,
Seth
