### ISSUE TITLE
Self-contained Executable 

### ISSUE THREAD

**Issue by downatone** [nickfloyd/newrelic-perfmon-plugin#2]
You mentioned 'Future versions will include a self-contained executable (stay tuned).'

Any eta on this, would be curious to try this out, but have never touched Ruby.

**Comment by pdxnam** [comment]
+1 interested in an eta on the exe as well!!!!

**Comment by sschwartzman** [comment]
We don't have an ETA on this yet - making an executable out of Ruby that can subsequently be run as a Windows service is proving to be a challenge. I will let you know when we make any progress on that front.

**Comment by pinkmist** [comment]
+18 here!

**Comment by sschwartzman** [comment]
Check it out, y'all! Ask and ye shall receive.

https://github.com/nickfloyd/newrelic-perfmon-plugin/blob/master/standalone/perfmon_plugin_standalone.zip

Let me know how it works for you. Instructions for it's use can be found in the main README.

**Comment by pinkmist** [comment]
Thanks chief.  I will give this a shot on Monday and let ya know.
