### ISSUE TITLE
Asp.net application where Perfmon Plugin not logging '.NET Data Provider for SqlServer' counts to New Relic

### ISSUE THREAD

**Issue by bhavinkumarp** [nickfloyd/newrelic-perfmon-plugin#21]
We have Asp.net application which is not logging '.NET Data Provider for SqlServer' counters to new relic 

We are using default counts only

find following Agent Configuration for the same
# 
# Agent Configuration:
# 

agents:
  perfmon:
      -
        local: yes
        hostname: localhost.xyz
        # Set "debug: true" to see metrics in stdout instead of sent to New Relic"
        debug: false
        # Set "testrun: tru

**Comment by sschwartzman** [comment]
Follow the steps defined here to add custom counters:
https://github.com/nickfloyd/newrelic-perfmon-plugin#collecting-custom-perfmon-counters-
