### ISSUE TITLE
New Relic Perfmon Plugin Service

### ISSUE THREAD

**Issue by JoeRAnaya** [nickfloyd/newrelic-perfmon-plugin#25]
Background Information:
New Installation
Windows Service Version
Installation Path - C:\Users\e_janaya\Downloads\NRPMSW\perfmon_plugin_standalone
Newrelic_plugin.yml - only inserted license key and hostname

Issue/Error:
The New Relic Perfmon Plugin service on Local Computer started and then stopped.  Some services stops automatically if they are not in use by other services or programs.

Event Log:
Log1 - Event ID 0
Starting C:\Users\e_janaya\Downloads\NRPMSW\perfmon_plugin_standalone\perfmon_plugin_standalone.exe 

Log2 - Event ID 0
Service cannot be started. System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at winsw.WrapperService.StartProcess(Process process, String arguments, String executable)
   at winsw.WrapperService.OnStart(String[] _)

**Comment by sschwartzman** [comment]
@JoeRAnaya I'd recommend using the Perfmon On-Host Integration for New Relic Infrastructure: https://github.com/newrelic/nri-perfmon

**Comment by JoeRAnaya** [comment]
Thank you Seth, let me give this a try.

Regards,
[Forward Slash]
[Elevate]
[cid:image003.gif@01D546E6.1DE70740]
Joe Anaya
Sr. Monitoring Engineer
P: (817) 928-1500 ext. 5251 | Elevate.com<http://www.elevate.com>
4150 International Plaza, Suite 300
Fort Worth, TX 76109

Privileged and Confidential. This e-mail, and any attachments thereto, is intended only for use by the addressee(s) named herein and may contain privileged and/or confidential information. If you have received this e-mail in error, please notify me immediately by a return e-mail and delete this e-mail. You are hereby notified that any dissemination, distribution or copying of this e-mail and/or any attachments thereto, is strictly prohibited.

**Comment by JoeRAnaya** [comment]
Hello Seth,

The Perfmon On-Host Integration worked like a charm.  Thank for the quick response and guidance – much appreciated.

Regards,
[Forward Slash]
[Elevate]
[cid:image003.gif@01D5479F.072D2930]
Joe Anaya
Sr. Monitoring Engineer
P: (817) 928-1500 ext. 5251 | Elevate.com<http://www.elevate.com>
4150 International Plaza, Suite 300
Fort Worth, TX 76109

Privileged and Confidential. This e-mail, and any attachments thereto, is intended only for use by the addressee(s) named herein and may contain privileged and/or confidential information. If you have received this e-mail in error, please notify me immediately by a return e-mail and delete this e-mail. You are hereby notified that any dissemination, distribution or copying of this e-mail and/or any attachments thereto, is strictly prohibited.

From: Joe Anaya
Sent: Tuesday, July 30, 2019 2:50 PM
To: nickfloyd/newrelic-perfmon-plugin <reply@reply.github.com>; nickfloyd/newrelic-perfmon-plugin <newrelic-perfmon-plugin@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [nickfloyd/newrelic-perfmon-plugin] New Relic Perfmon Plugin Service (#25)

Thank you Seth, let me give this a try.

Regards,
[Forward Slash]
[Elevate]
[cid:image003.gif@01D5479F.072D2930]
Joe Anaya
Sr. Monitoring Engineer
P: (817) 928-1500 ext. 5251 | Elevate.com<http://www.elevate.com>
4150 International Plaza, Suite 300
Fort Worth, TX 76109

Privileged and Confidential. This e-mail, and any attachments thereto, is intended only for use by the addressee(s) named herein and may contain privileged and/or confidential information. If you have received this e-mail in error, please notify me immediately by a return e-mail and delete this e-mail. You are hereby notified that any dissemination, distribution or copying of this e-mail and/or any attachments thereto, is strictly prohibited.

**Comment by sschwartzman** [comment]
Great news @JoeRAnaya! Just curious, did you use the OOTB config, one of the extras packaged with it, or your own custom one?

I'm going to close this out since we're done here. :) But feel free to write up any issues in nri-perfmon if any should arise.
