### ISSUE TITLE
bundle install

### ISSUE THREAD

**Issue by pdxnam** [nickfloyd/newrelic-perfmon-plugin#3]
Getting this error when trying to run 'bundle install'.  Am I missing something?

Fetching gem metadata from http://rubygems.org/.........
Fetching gem metadata from http://rubygems.org/..
Fetching git@github.com:newrelic-platform/newrelic_plugin.git
Unfortunately, a fatal error has occurred. Please see the Bundler
troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/source/git/git_pro
xy.rb:88:in ``': No such file or directory - git clone "git@github.com:newrelic-
platform/newrelic_plugin.git" "C:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/
newrelic_plugin-ee26a2accbf47c00562443b80ad79aaa92b63420" --bare --no-hardlinks
(Errno::ENOENT)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/sourc
e/git/git_proxy.rb:88:in`git'

**Comment by sschwartzman** [comment]
The Gemfile needed to be updated to reflect the new location for the newrelic_plugin gem. Can you please pull down that file, try the bundle install again, and then let me know if that worked?

**Comment by sschwartzman** [comment]
Updated Gemfile.lock as well, so please pull that too.

**Comment by pdxnam** [comment]
Fixed!!!  Thanks!!!!
