### ISSUE TITLE
Perfmon plugin standalone

### ISSUE THREAD

**Issue by pdxnam** [nickfloyd/newrelic-perfmon-plugin#5]
I tried running the standalone .exe on a windows server, but it seems to be looking for ruby.

**Comment by sschwartzman** [comment]
Can you show us the command you're running and the message you get?

**Comment by pdxnam** [comment]
C:\temp\newrelic-perfmon-plugin\standalone\perfmon_plugin_standalone\perfmon_plu
gin_standalone>perfmon_plugin_standalone.exe
←[31mCould not find newrelic_plugin-1.0.2 in any of the sources←[0m
←[33mRun `bundle install` to install missing gems.←[0m

C:\temp\newrelic-perfmon-plugin\standalone\perfmon_plugin_standalone\perfmon_plu
gin_standalone>

**Comment by sschwartzman** [comment]
I've re-built the plugin to include the gems it needs, so it shouldn't expect anything from ruby now in the standalone exe. Please give it a try, re-open this ticket if there are any issues.

Thanks,
Seth
