### ISSUE TITLE
multiple hostnames

### ISSUE THREAD

**Issue by mordamus** [nickfloyd/newrelic-perfmon-plugin#6]
I want to monitor multiple servers. How can i enter these in the config?

```
    local: 
    hostname: server1
    # Set "debug: true" to see metrics in stdout instead of sent to New Relic"
    debug: false
    # Set "testrun: true" to use input from local text/html files. Only parses input once, then quits.
    testrun: false
```

**Comment by sschwartzman** [comment]
You do so like this:

```
agents:
  perfmon:
      -
        local: no
        hostname: remote_server1
        debug: false
        testrun: false
      -
        local: no
        hostname: remote_server1
        debug: false
        testrun: false
      -
        local: yes
        hostname: local_server
        debug: false
        testrun: false
```

So, for every server you want to monitor, add a stanza. Make sure to use the same spacing - YML can be finicky. Also, yes, you can combine local and remote servers in the same agent - as you see above, this example would create 2 instances for remote servers and 1 instance for localhost.

Let us know if that works for you.
