### ISSUE TITLE
Edit Perfmon Counters - Windows

### ISSUE THREAD

**Issue by danfoxley** [nickfloyd/newrelic-perfmon-plugin#8]
From this readme: 
## https://github.com/nickfloyd/newrelic-perfmon-plugin/blob/master/README.md

```
 [Edit perfmon counters - Ruby]
      Edit 'config\perfmon_counters.txt' to list which counters you wish to collect
      Execute perfmon_plugins_multithread.rb at command-line
```

---

I see the option to edit perfmon counters for Ruby, but nothing similar for Windows, and I don't see the associated files (.rb and .txt) in the Windows .zip package.  How can I edit which perfmon counters the plugin gathers?

**Comment by sschwartzman** [comment]
As the plugin stands today, you'll have to use the rub, and furthermore fork the plugin. The reason being, if it reports with the same GUID as the standard one, you will get the standard dashboards, which are immutable (for all plugins). But if you change the GUID, you can make any changes to the counters list and then create dashboards for them.

I'm considering making the change-of-GUID process easier such that it wouldn't require a rebuild of the EXE, but we may focus our efforts on porting this to native .NET code. I'll keep you posted. In the meantime, you'll need to use the ruby code if you want to do this - you can use the Ruby version provided you have installed the prerequisites listed in the README: https://github.com/nickfloyd/newrelic-perfmon-plugin/blob/master/README.md#prerequisites

--Seth

**Comment by danfoxley** [comment]
Ah, ha.  I'll see about using the ruby version then, and would look forward to the possible rebuild of the EXE to allow this for the .NET code.

Thanks,
Dan

**Comment by sschwartzman** [comment]
I've updated the code such that the GUID is now in the config file. I just have to do a little testing and rebuild the EXE, and you should be on your way! Stay tuned.

**Comment by sschwartzman** [comment]
Updated the standalone EXE to allow for custom counters. Please give it a try, re-open this ticket if there are any issues.

Thanks,
Seth

**Comment by danfoxley** [comment]
Hi Seth,

I will install the standalone EXE.  In the meantime, I got the ruby version
working and posting to NR using a new GUID.  Can I ask a few questions, to
clarify?

1.
In the screenshot below,  when I selected a perfmon counter in NewRelic I
get "ms" instead of the expected "s" (milliseconds vs. seconds).  Is there
a place I can change these?

2.
I'm guessing perfmon_metrics.rb has something to do with #1 and other
perfmon properties when displayed on New Relic. How would I use this/or
other to adjust the display of custom perfmon data I'd like to post to
NewRelic?  If that is correct, I don't see this file for the .exe version.

Thanks for your time,
Dan Foxley

[image: Inline image 1]

**Comment by sschwartzman** [comment]
Hi Dan,

You are right, the perfmon_metrics.rb file exists to apply metric types to each counter. This is because the Ruby Plugin SDK requires metric type when sending the metric to New Relic.

As it stands today, you'll need to edit that file to get the counters to not show up as "ms". This would entail forking the project rather than using the EXE. I figure that .rb file could be changed into a config file, or a config file could be created to add to that list for any custom counters, but its a little clunky. If you have a better idea of how to accomplish this (or some Ruby chops to write up the code), please let me know!

Thanks for the feedback,
Seth

**Comment by danfoxley** [comment]
Hey Seth,

Thanks for the reply. As it is, I'm over my head on this, I'm surprised I
got the Ruby version installed/running. I'll have to bow out or use the
ruby version as is. I wouldn't know where to begin to re-architect or build
new code, I was just able to piece the logic together to get the Ruby
version running.

Dan
